language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - mkdir -p build/logs
  - ./bin/setup_phync_development

script: phpunit --coverage-text

after_script: ./bin/run_coveralls
